modLoader="javafml"
loaderVersion="[31,34]"
license="Legopitstop & Sir_Craftypants Common License"
issueTrackerURL="https://github.com/legopitstop/LotsMoreFood-1.16.1/issues"

[[mods]]
modId="morefood"
version="1.2.0"
displayName="Lot's More Food"
updateJSONURL="https://github.com/legopitstop/ModUpdates/raw/master/LotsMoreFood/update.json"
displayURL="https://www.curseforge.com/members/legopitstop/projects"
logoFile="mod_banner.png"
credits="Now available for forge!"
authors="Legopitstop & Sir_Craftypants"
description='''
 Ever thought that Minecraft needed more food? Then this is your mod! This mod adds more than 200+ Foods. Use to replenish those health and hunger points.
'''

[[dependencies.morefood]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morefood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
